# Generated by Django 5.1.3 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_workoutschedule_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
