# Generated by Django 5.1.3 on 2024-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=50),
        ),
    ]
