# Generated by Django 5.1.3 on 2024-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_workoutschedule_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
