# Generated by Django 5.1.3 on 2024-12-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_workoutschedule_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
